apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: staging-

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: geosentinel-config
    data:
      APP_ENV: "staging"
      APP_DEBUG: "true"
