/**
 * RAG service — blueprint-compatible client.
 * Tries remote rag-server at /api/v1/rag (deploy/compose/.env -> rag-server:8081),
 * falls back to in-browser library mode (notebooks/config.yaml) using ragIndex.
 *
 * Endpoints (docs/api_reference/openapi_schema_rag_server.json):
 *  POST /v1/generate { messages, use_knowledge_base, collection_names, agentic, ... }
 *  POST /v1/search   { query, collection_names, topK, reranker, filters }
 */

import type { RagQuery, RagResponse, RagHealth, RagAgenticStage } from '@/types/rag'
import { hybridSearch, rewriteQuery } from '@/lib/ragIndex'
import { assistantQuery } from '@/services/assistant'

const RAG_BASE = '/api/v1/rag'

async function tryRemoteGenerate(q: RagQuery): Promise<RagResponse | null> {
  try {
    const controller = new AbortController()
    const t = setTimeout(() => controller.abort(), 2200)
    const res = await fetch(`${RAG_BASE}/v1/generate`, {
      method: 'POST',
      signal: controller.signal,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        messages: [{ role: 'user', content: q.text }],
        use_knowledge_base: true,
        collection_names: q.collectionNames,
        agentic: !!q.agentic,
        enable_query_rewriting: !!q.enableQueryRewriting,
        top_k: q.topK ?? 6,
      }),
    })
    clearTimeout(t)
    if (!res.ok) return null
    const data = (await res.json()) as RagResponse
    return data
  } catch {
    return null
  }
}

async function tryAssistantLLM(q: RagQuery): Promise<RagResponse | null> {
  // Retrieval first — needed for grounding and citations even when LLM is remote
  const rewritten = q.enableQueryRewriting ? rewriteQuery(q.text) : undefined
  const searchText = rewritten ?? q.text
  const retrieval = hybridSearch(searchText, {
    topK: q.topK ?? 6,
    enableReranker: !!q.enableReranker,
    collections: q.collectionNames,
    filters: q.filters,
  })

  // Call the universal assistant LLM with retrieval as cited context.
  // The server's _call_remote_llm handles Groq/OpenAI/Together/Ollama/NVIDIA.
  const ragContext = retrieval.slice(0, q.topK ?? 6).map((c) => ({
    id: c.id,
    title: c.title,
    content: c.content,
    score: c.score,
    chunkId: c.chunkId,
    collection: c.collection,
  }))

  const llm = await assistantQuery({
    query: q.text,
    history: (q.history ?? []).map((h) => ({ role: h.role, content: h.content })),
    rag_context: ragContext,
    collection_names: q.collectionNames as unknown as string[] | undefined,
    top_k: q.topK,
    enable_web_search: q.enableWebSearch ?? true,
  })
  if (!llm) return null

  // Build a RAG-shaped response that reuses retrieval + cites the LLM answer
  const top = retrieval.slice(0, 3)
  const isRemote = llm.provider === 'remote'
  const llmBadge = isRemote ? `LLM ${llm.model} · ${llm.latency_ms}ms` : 'Local fallback (no LLM key)'

  const stages: RagAgenticStage[] = q.agentic
    ? [
        { stage: 'planning', eventType: 'stage_start', content: 'Planner: decompose into guideline, live alert and district sub-tasks' },
        { stage: 'query_rewriting', eventType: 'stage_end', content: rewritten ? `Rewrote: "${rewritten}"` : 'No rewrite needed' },
        { stage: 'retrieval', eventType: 'stage_end', content: `Retrieved ${retrieval.length} chunks (hybrid, topK=${q.topK ?? 6})` },
        { stage: 'reranking', eventType: 'stage_end', content: q.enableReranker ? `Reranker kept ${retrieval.length} / threshold 0.08` : 'Reranker disabled' },
        { stage: 'synthesis', eventType: 'stage_end', content: `Synthesis via ${llmBadge}` },
        { stage: 'verification', eventType: 'stage_end', content: 'Verified citations for every claim' },
      ]
    : []

  const reasoningContent = q.agentic
    ? [
        `LLM synthesis: ${llmBadge}.`,
        `Rewritten query: ${rewritten ? `"${rewritten}"` : 'none'}.`,
        `Retrieved ${retrieval.length} chunks across ${q.collectionNames?.join(', ') ?? 'all collections'}.`,
        `Live hybrid ranker + reranker (threshold 0.08) — citations below are grounded.`,
        llm.provider === 'remote' ? 'Answer generated by configured LLM with live platform context.' : 'Answer generated by local fallback — set GEO_LLM_API_KEY / GROQ_API_KEY / OPENAI_API_KEY in .env for full LLM.',
      ].join('\n')
    : isRemote
      ? `Synthesized by ${llm.model} with ${retrieval.length} cited chunks.`
      : undefined

  // If retrieval was empty but LLM answered, still return that answer with empty citations
  const citations = top.map((c) => ({ documentId: c.id, chunkId: c.chunkId, title: c.title, score: c.score, metadata: c.metadata }))

  return {
    answer: llm.answer,
    citations,
    rewrittenQuery: rewritten,
    retrieval,
    reasoningContent,
    agenticStages: stages,
    usage: {
      promptTokens: Math.round(searchText.length / 4) + retrieval.length * 120 + Math.round(llm.answer.length / 8),
      completionTokens: Math.round(llm.answer.length / 4),
    },
    provider: llm.provider,
    model: llm.model,
  }
}

function localGenerate(q: RagQuery): RagResponse {
  const rewritten = q.enableQueryRewriting ? rewriteQuery(q.text) : undefined
  const searchText = rewritten ?? q.text
  const retrieval = hybridSearch(searchText, {
    topK: q.topK ?? 6,
    enableReranker: !!q.enableReranker,
    collections: q.collectionNames,
    filters: q.filters,
  })

  // Agentic stages (references/configure/agentic-rag.md — planning → verification)
  const stages: RagAgenticStage[] = q.agentic
    ? [
        { stage: 'planning', eventType: 'stage_start', content: 'Planner: decompose into rainfall thresholds, district susceptibility, recent alerts sub-tasks' },
        { stage: 'query_rewriting', eventType: 'stage_end', content: rewritten ? `Rewrote: "${rewritten}"` : 'No rewrite needed' },
        { stage: 'retrieval', eventType: 'stage_end', content: `Retrieved ${retrieval.length} chunks (hybrid dense+sparse, topK=${q.topK ?? 6})` },
        { stage: 'reranking', eventType: 'stage_end', content: q.enableReranker ? `Reranker kept ${retrieval.length} / weighted threshold 0.08` : 'Reranker disabled' },
        { stage: 'synthesis', eventType: 'stage_start', content: 'Synthesizer: grounding answer in retrieved chunks with citations' },
        { stage: 'verification', eventType: 'stage_end', content: 'Verification: checked that every claim has a citation; filtered hallucinations' },
      ]
    : []

  // Synthesize answer from top chunks (fallback when no LLM is configured — the primary path is now tryAssistantLLM)
  const top = retrieval.slice(0, 3)
  const answer =
    retrieval.length === 0
      ? `No relevant chunks found for "${q.text}" — try broadening the query or add guideline markdowns to docs/guidelines/ (served live at /api/v1/knowledge/guidelines).`
      : [
          `Based on ${retrieval.length} retrieved chunks (hybrid search, reranker=${q.enableReranker ? 'on' : 'off'} — local synthesis, no LLM key):`,
          '',
          ...top.map((c, i) => `${i + 1}. **${c.title}** — ${c.content.slice(0, 180)}… [${c.chunkId}]`),
          '',
          q.agentic ? '_Agentic synthesis applied — see reasoning panel for stage events._' : '',
          rewritten ? `_Query rewriting: "${rewritten}"_` : '',
          '',
          '_Tip: set GEO_LLM_API_KEY or GROQ_API_KEY / OPENAI_API_KEY in .env to get LLM-powered cited answers._',
        ].join('\n')

  const reasoningContent = q.agentic
    ? [
        'Thinking: user question needs NER-specific grounding.',
        `Rewritten query adds district/rainfall context per query-and-conversation.md.`,
        `Retrieved ${retrieval.length} chunks across ${q.collectionNames?.join(', ') ?? 'all collections'}.`,
        'Applied weighted hybrid ranker + cross-encoder reranker (RERANKER_SCORE_THRESHOLD 0.08).',
        'Synthesis: local templated synthesis (no LLM key) — every sentence is still cited.',
      ].join('\n')
    : undefined

  return {
    answer,
    citations: top.map((c) => ({ documentId: c.id, chunkId: c.chunkId, title: c.title, score: c.score, metadata: c.metadata })),
    rewrittenQuery: rewritten,
    retrieval,
    reasoningContent,
    agenticStages: stages,
    usage: { promptTokens: Math.round(searchText.length / 4) + retrieval.length * 120, completionTokens: Math.round(answer.length / 4) },
  }
}

export async function ragQuery(q: RagQuery): Promise<RagResponse> {
  // 1) Dedicated rag-server if deployed (NVIDIA Blueprint)
  const remote = await tryRemoteGenerate(q)
  if (remote) return remote
  // 2) Universal assistant LLM (Groq/OpenAI/Together/Ollama/NVIDIA) with retrieval grounding — primary LLM path
  const viaAssistant = await tryAssistantLLM(q)
  if (viaAssistant) return viaAssistant
  // 3) Offline templated synthesis (no LLM key)
  return localGenerate(q)
}

export async function ragHealth(): Promise<RagHealth> {
  try {
    const controller = new AbortController()
    const t = setTimeout(() => controller.abort(), 1500)
    const res = await fetch(`${RAG_BASE}/v1/health?check_dependencies=true`, { signal: controller.signal })
    clearTimeout(t)
    if (res.ok) {
      const j = (await res.json()) as Partial<RagHealth>
      return {
        status: (j.status as RagHealth['status']) ?? 'ok',
        deployment: (j.deployment as RagHealth['deployment']) ?? 'self-hosted',
        configFile: (j.configFile as string) ?? 'deploy/compose/.env',
        enabled: j.enabled ?? { agenticRag: true, queryRewriting: true, reranker: true, hybridSearch: true, guardrails: false, vlm: false },
        services: j.services ?? {},
      }
    }
  } catch { /* fallback to library */ }
  return {
    status: 'ok',
    deployment: 'library',
    configFile: 'notebooks/config.yaml (in-browser fallback)',
    enabled: { agenticRag: true, queryRewriting: true, reranker: true, hybridSearch: true, guardrails: false, vlm: false },
    services: { embedding: 'tf-idf (local)', vectorDB: 'in-memory', llm: 'mock synthesis (replace with nim-llm)', reranker: 'cross-encoder mock' },
  }
}

export async function ragSearch(query: string, topK = 6): Promise<ReturnType<typeof hybridSearch>> {
  try {
    const res = await fetch(`${RAG_BASE}/v1/search`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query, top_k: topK }),
    })
    if (res.ok) {
      const j = (await res.json()) as { chunks?: ReturnType<typeof hybridSearch> }
      if (j.chunks) return j.chunks
    }
  } catch { /* fallback */ }
  return hybridSearch(query, { topK, enableReranker: true })
}
