apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: geosentinel
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:16-3.4
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: geosentinel
            - name: POSTGRES_USER
              value: geosentinel_admin
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: geosentinel-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: geosentinel
spec:
  type: ClusterIP
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
