import { useCallback, useMemo, useRef, useState } from 'react'
import { DEFAULT_INPUTS, SUPPORTED_FORMATS } from '@/types/simready'
import type { SimReadyInputs, SimReadyReport, StageReport } from '@/types/simready'
import { WORKFLOW_STEPS, extFromPath } from '@/lib/simreadyWorkflow'
import { simulateWorkflow, validateInputs } from '@/services/simready'

const STATUS_META: Record<StageReport['status'], { label: string; cls: string; dot: string }> = {
  pending: { label: 'pending', cls: 'border-slate-700 text-slate-500', dot: 'bg-slate-600' },
  running: { label: 'running', cls: 'border-cyan-500/50 bg-cyan-500/10 text-cyan-300', dot: 'bg-cyan-400 animate-pulse' },
  passed: { label: 'passed', cls: 'border-emerald-500/40 bg-emerald-500/10 text-emerald-300', dot: 'bg-emerald-400' },
  needs_rerun: { label: 'needs_rerun', cls: 'border-amber-500/40 bg-amber-500/10 text-amber-300', dot: 'bg-amber-400' },
  blocked: { label: 'blocked', cls: 'border-rose-500/40 bg-rose-500/10 text-rose-300', dot: 'bg-rose-400' },
  failed: { label: 'failed', cls: 'border-rose-500/40 bg-rose-500/10 text-rose-300', dot: 'bg-rose-400' },
  skipped: { label: 'skipped', cls: 'border-slate-700/60 bg-slate-800/40 text-slate-500', dot: 'bg-slate-600' },
}

function ReportMarkdown({ report }: { report: SimReadyReport }) {
  const md = useMemo(() => {
    return `# Omniverse CAD → SimReady — GeoSentinel Terrain Lab
**Overall:** ${report.passed ? '✅ passed' : report.needs_rerun ? '⚠️ needs_rerun' : '❌ blocked'} · profile \`${report.simready_profile}\` · intent \`${report.property_assignment_status}\`

| Field | Value |
|---|---|
| source_asset_path | \`${report.source_asset_path}\` |
| source_format | \`${report.source_format}\` |
| output_root | \`${report.output_root}\` |
| output_usd_path | \`${report.output_usd_path ?? '—'}\` |
| conformed_usd_path | \`${report.conformed_usd_path ?? '—'}\` |
| render_preview_path | \`${report.render_preview_path ?? '—'}\` |
| deliverable_root | \`${report.deliverable_root ?? '—'}\` |
| passed | \`${String(report.passed)}\` |
| needs_rerun | \`${String(report.needs_rerun)}\` |
| generated_at | \`${report.generated_at}\` |

## Stage results
${report.steps.map((s) => `- **${s.title}** — \`${s.status}\`${s.message ? ` — ${s.message}` : ''}`).join('\n')}

## Validation gates
${report.validation_gates.map((g) => `- **${g.id}** (${g.requirement}) — \`${g.status}\` · ${g.findings} finding(s)`).join('\n')}

## Next steps
${report.needs_rerun ? '- One profile finding needs a follow-up repair pass (grasp/physics refinement).' : '- No rerun required — asset is simulation-ready and packaged.'}
${report.rerun_reasons.length ? `\nRerun reasons:\n${report.rerun_reasons.map((r) => `- ${r}`).join('\n')}` : ''}

---
_Generated by GeoSentinel-NER SimReady Lab._
`
  }, [report])
  return (
    <pre className="whitespace-pre-wrap break-words rounded-lg border border-slate-800 bg-slate-950 p-3 text-[12px] leading-relaxed text-slate-300">
      {md}
    </pre>
  )
}

function SlopeDemo() {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const rafRef = useRef<number | null>(null)
  const [running, setRunning] = useState(false)
  const [cohesion, setCohesion] = useState(0.35)
  const [friction, setFriction] = useState(0.62)

  const run = useCallback(() => {
    const c = canvasRef.current
    if (!c) return
    const ctx = c.getContext('2d')
    if (!ctx) return
    const W = c.width
    const H = c.height
    // slope line: from (0, H*0.35) to (W, H*0.82)
    const slopeY = (x: number) => H * 0.35 + (x / W) * (H * 0.47)
    const particles = Array.from({ length: 80 }, (_, i) => ({
      x: 20 + (i % 10) * 14 + Math.random() * 6,
      y: slopeY(20 + (i % 10) * 14) - 8 - Math.random() * 18,
      vx: 0,
      vy: 0,
      r: 2 + Math.random() * 2.2,
    }))
    let t = 0
    const g = 0.45
    const k = 0.02
    const tick = () => {
      t += 1
      ctx.clearRect(0, 0, W, H)
      // sky
      ctx.fillStyle = '#020617'
      ctx.fillRect(0, 0, W, H)
      // terrain fill
      ctx.fillStyle = '#1e293b'
      ctx.beginPath()
      ctx.moveTo(0, H)
      ctx.lineTo(0, slopeY(0))
      for (let x = 0; x <= W; x += 2) ctx.lineTo(x, slopeY(x))
      ctx.lineTo(W, H)
      ctx.closePath()
      ctx.fill()
      // slope line
      ctx.strokeStyle = 'rgba(56,189,248,0.35)'
      ctx.lineWidth = 1
      ctx.beginPath()
      ctx.moveTo(0, slopeY(0))
      for (let x = 0; x <= W; x += 1) ctx.lineTo(x, slopeY(x))
      ctx.stroke()
      // info
      ctx.fillStyle = 'rgba(148,163,184,0.9)'
      ctx.font = '10px ui-monospace, monospace'
      const fContent = `C=${cohesion.toFixed(2)}  φ=${(Math.atan(friction) * 180 / Math.PI).toFixed(0)}°  t=${t}`
      ctx.fillText(fContent, 8, 14)
      const stability = cohesion + friction * 0.6
      const slideProb = Math.max(0, Math.min(1, 1 - stability))
      // particles
      for (const p of particles) {
        // slope normal at p.x
        const sx = slopeY(p.x)
        const onSlope = p.y + p.r >= sx - 2
        if (onSlope) {
          const slopeAngle = Math.atan2(slopeY(p.x + 2) - slopeY(p.x - 2), 4)
          const gs = g * Math.sin(slopeAngle) // downslope component
          const gn = g * Math.cos(slopeAngle) // normal
          const resist = cohesion * 0.9 + gn * friction
          const a = Math.max(0, gs - resist * k)
          // downslope is +x and +y
          p.vx += a * Math.cos(slopeAngle) + (Math.random() - 0.5) * 0.02
          p.vy += a * Math.sin(slopeAngle) + (Math.random() - 0.5) * 0.02
          // friction damping when stable
          if (slideProb < 0.25) { p.vx *= 0.96; p.vy *= 0.96 }
        } else {
          p.vy += g * 0.06
          p.vx += (Math.random() - 0.5) * 0.01
        }
        p.x += p.vx
        p.y += p.vy
        // collide with slope
        const sy = slopeY(p.x)
        if (p.y + p.r > sy) { p.y = sy - p.r; p.vy *= 0.35; p.vx *= 0.9 }
        if (p.x < 0 || p.x > W) { p.vx *= -0.6; p.x = Math.max(0, Math.min(W, p.x)) }
        ctx.fillStyle = p.vy > 0.7 ? 'rgba(251,113,133,0.95)' : 'rgba(148,163,184,0.95)'
        ctx.beginPath()
        ctx.arc(p.x, p.y, p.r, 0, Math.PI * 2)
        ctx.fill()
      }
      if (t < 620) rafRef.current = requestAnimationFrame(tick)
      else setRunning(false)
    }
    rafRef.current = requestAnimationFrame(tick)
  }, [cohesion, friction])

  const handleRun = () => {
    if (rafRef.current) cancelAnimationFrame(rafRef.current)
    setRunning(true)
    run()
  }
  const handleStop = () => {
    if (rafRef.current) cancelAnimationFrame(rafRef.current)
    setRunning(false)
  }

  return (
    <div className="rounded-xl border border-slate-800 bg-slate-950 p-3">
      <div className="mb-2 flex items-center justify-between">
        <div className="text-xs font-semibold uppercase tracking-wider text-slate-400">Landslide physics · slope demo</div>
        <span className="rounded-full border border-cyan-500/30 bg-cyan-500/10 px-2 py-0.5 text-[11px] text-cyan-300">SimReady Physics (preview)</span>
      </div>
      <canvas ref={canvasRef} width={560} height={200} className="w-full rounded-lg border border-slate-800 bg-[#020617]" />
      <div className="mt-3 grid grid-cols-2 gap-3">
        <label className="text-xs text-slate-400">
          Cohesion C
          <input type="range" min={0} max={1} step={0.01} value={cohesion} onChange={(e) => setCohesion(Number(e.target.value))} className="mt-1 w-full accent-cyan-500" />
        </label>
        <label className="text-xs text-slate-400">
          Friction µ
          <input type="range" min={0.1} max={1} step={0.01} value={friction} onChange={(e) => setFriction(Number(e.target.value))} className="mt-1 w-full accent-cyan-500" />
        </label>
      </div>
      <div className="mt-3 flex gap-2">
        <button onClick={handleRun} disabled={running} className="rounded-lg bg-cyan-500 px-3 py-1.5 text-xs font-semibold text-slate-950 hover:bg-cyan-400 disabled:opacity-50">▶ Run slide</button>
        <button onClick={handleStop} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800">Stop</button>
        <span className="ml-auto text-[11px] leading-5 text-slate-500">After USD physics assignment, this runs in Isaac Sim with USD Physics colliders.</span>
      </div>
    </div>
  )
}

export default function SimReadyLab() {
  const [inputs, setInputs] = useState<SimReadyInputs>({ ...DEFAULT_INPUTS })
  const [dragOver, setDragOver] = useState(false)
  const [stages, setStages] = useState<StageReport[] | null>(null)
  const [report, setReport] = useState<SimReadyReport | null>(null)
  const [running, setRunning] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const fileRef = useRef<HTMLInputElement>(null)

  const chosenExt = extFromPath(inputs.sourceAssetPath).toLowerCase()
  const route = chosenExt ? SUPPORTED_FORMATS[chosenExt] : undefined

  const handleFiles = useCallback((files: FileList | null) => {
    const f = files?.[0]
    if (!f) return
    const ext = extFromPath(f.name).toLowerCase()
    setInputs((s) => ({ ...s, sourceAsset: f, sourceAssetPath: f.name, sourceFormat: ext }))
    setStages(null)
    setReport(null)
    setError(null)
  }, [])

  const onDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    setDragOver(false)
    handleFiles(e.dataTransfer.files)
  }, [handleFiles])

  const runWorkflow = useCallback(async () => {
    const err = validateInputs(inputs)
    if (err) { setError(err); return }
    setError(null)
    setRunning(true)
    setStages(WORKFLOW_STEPS.map((s) => ({ stage: s.id, title: s.label, status: 'pending' as const })))
    setReport(null)
    try {
      const r = await simulateWorkflow(inputs, (stage) => {
        setStages((prev) => {
          if (!prev) return prev
          const next = [...prev]
          const idx = next.findIndex((x) => x.stage === stage.stage)
          if (idx >= 0) next[idx] = stage
          return next
        })
      })
      setReport(r)
      // finalize stages from report (covers needs_rerun etc.)
      setStages(r.steps)
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setRunning(false)
    }
  }, [inputs])

  const downloadJson = useCallback(() => {
    if (!report) return
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'omniverse-cad-to-simready-report.json'
    a.click()
    URL.revokeObjectURL(url)
  }, [report])

  const downloadMd = useCallback(() => {
    if (!report) return
    // reconstruct markdown via ReportMarkdown logic — simpler: serialize report JSON as md placeholder
    const md = `# SimReady Report\n\n\`\`\`json\n${JSON.stringify(report, null, 2)}\n\`\`\`\n`
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'omniverse-cad-to-simready-report.md'
    a.click()
    URL.revokeObjectURL(url)
  }, [report])

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="solid-card overflow-hidden rounded-xl">
        <div className="flex flex-col gap-3 bg-gradient-to-br from-cyan-500/10 via-violet-500/10 to-fuchsia-500/10 px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-lg font-extrabold tracking-tight">
              SimReady Terrain Lab <span className="text-[#38BDF8]">· CAD → USD simulation-ready terrain</span>
            </h2>
            <p className="mt-1 max-w-2xl text-xs leading-relaxed text-slate-400">
              Convert NER hillslope DEMs and mitigation CAD into physics-ready USD for landslide runout simulation.
              Pipeline: preflight → convert → validate → conform → validation gates → render → package.
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-4 xl:grid-cols-[420px_minmax(0,1fr)]">
        {/* LEFT — inputs */}
        <div className="space-y-4">
          <div className="solid-card rounded-xl p-4">
            <h3 className="text-sm font-bold">1. Source asset</h3>
            <p className="mt-1 text-xs text-slate-500">Drop a CAD / mesh / DEM / USD file. Source is never moved — workflow writes under <code className="font-mono text-[11px]">output_root</code>.</p>

            {/* Drop zone */}
            <div
              onDragOver={(e) => { e.preventDefault(); setDragOver(true) }}
              onDragLeave={() => setDragOver(false)}
              onDrop={onDrop}
              onClick={() => fileRef.current?.click()}
              role="button"
              tabIndex={0}
              onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') fileRef.current?.click() }}
              className={`mt-3 flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed px-4 py-8 text-center transition ${
                dragOver ? 'border-cyan-400 bg-cyan-500/10' : 'border-slate-700 bg-slate-900/50 hover:border-slate-600'
              }`}
            >
              <div className="text-2xl">⬢</div>
              <div className="mt-1 text-sm font-semibold text-slate-200">{inputs.sourceAsset ? inputs.sourceAsset.name : 'Drop CAD / USD / DEM here'}</div>
              <div className="text-xs text-slate-500">or click to browse ·  STEP, STP, OBJ, FBX, glTF, STL, PLY, USD, GeoTIFF</div>
              <div className="mt-2 text-[11px] font-mono text-slate-600">{inputs.sourceAssetPath || 'no file selected'}</div>
            </div>
            <input ref={fileRef} type="file" className="hidden" accept=".step,.stp,.obj,.fbx,.gltf,.glb,.dae,.stl,.ply,.spz,.usd,.usda,.usdc,.usdz,.tif,.tiff,.xml,.urdf,.zip" onChange={(e) => handleFiles(e.target.files)} />

            {chosenExt && (
              <div className={`mt-3 rounded-lg border px-3 py-2 text-xs ${route?.supported ? 'border-emerald-500/20 bg-emerald-500/5 text-emerald-300' : 'border-rose-500/20 bg-rose-500/5 text-rose-300'}`}>
                <div className="font-mono text-[11px] text-slate-400">.{chosenExt} → {route?.route ?? 'unsupported'}</div>
                {route?.supported ? '✓ Routed via convert-to-usd (or direct validate for USD)' : '✗ Unsupported — see Source Routing table (workflow.md)'}
              </div>
            )}

            <div className="mt-4 space-y-3">
              <label className="block">
                <span className="text-xs font-semibold text-slate-300">output_root</span>
                <input value={inputs.outputRoot} onChange={(e) => setInputs((s) => ({ ...s, outputRoot: e.target.value }))} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 font-mono text-xs text-slate-200 placeholder:text-slate-600" placeholder="/tmp/geosentinel-simready/run-01" />
                <span className="text-[11px] text-slate-500">Holds <code className="font-mono">pipeline/</code> + <code className="font-mono">deliverable/</code> (two-zone layout, per assemble-package-source)</span>
              </label>

              <div className="grid grid-cols-2 gap-3">
                <label className="block">
                  <span className="text-xs font-semibold text-slate-300">SimReady profile</span>
                  <select value={inputs.simreadyProfile} onChange={(e) => setInputs((s) => ({ ...s, simreadyProfile: e.target.value as SimReadyInputs['simreadyProfile'] }))} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-2 py-2 text-xs text-slate-200">
                    <option value="Prop-Robotics-Neutral">Prop-Robotics-Neutral (terrain prop)</option>
                    <option value="Robot-Body-Runnable">Robot-Body-Runnable (URDF/MJCF)</option>
                    <option value="Custom">Custom</option>
                  </select>
                </label>
                <label className="block">
                  <span className="text-xs font-semibold text-slate-300">property_assignment_intent</span>
                  <select value={inputs.propertyAssignmentIntent} onChange={(e) => setInputs((s) => ({ ...s, propertyAssignmentIntent: e.target.value as SimReadyInputs['propertyAssignmentIntent'] }))} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-900 px-2 py-2 text-xs text-slate-200">
                    <option value="skip">skip (conversion-only) — Windows-safe</option>
                    <option value="run">run (Material+Physics) — needs GPU</option>
                  </select>
                </label>
              </div>

              <div className="flex gap-4">
                <label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={inputs.enablePreview} onChange={(e) => setInputs((s) => ({ ...s, enablePreview: e.target.checked }))} className="h-4 w-4 rounded border-slate-600 bg-slate-800 accent-cyan-500" /> OVRTX preview</label>
                <label className="flex items-center gap-2 text-xs text-slate-300"><input type="checkbox" checked={inputs.enablePackage} onChange={(e) => setInputs((s) => ({ ...s, enablePackage: e.target.checked }))} className="h-4 w-4 rounded border-slate-600 bg-slate-800 accent-cyan-500" /> Package deliverable</label>
              </div>
              {inputs.enablePackage && (
                <div className="grid grid-cols-2 gap-3">
                  <input value={inputs.packageName} onChange={(e) => setInputs((s) => ({ ...s, packageName: e.target.value }))} placeholder="asset_name" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 font-mono text-xs" />
                  <input value={inputs.packageVersion} onChange={(e) => setInputs((s) => ({ ...s, packageVersion: e.target.value }))} placeholder="1.0.0" className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 font-mono text-xs" />
                </div>
              )}

              <details className="rounded-lg border border-slate-800 bg-slate-900/50">
                <summary className="cursor-pointer px-3 py-2 text-xs font-semibold text-slate-300">Supported source formats</summary>
                <div className="max-h-40 overflow-auto border-t border-slate-800 p-2">
                  <table className="w-full text-left text-[11px]">
                    <thead><tr className="text-slate-500"><th className="px-2 py-1">ext</th><th className="px-2 py-1">route</th></tr></thead>
                    <tbody>
                      {Object.entries(SUPPORTED_FORMATS).map(([ext, v]) => (
                        <tr key={ext} className="odd:bg-slate-800/20"><td className="px-2 py-1 font-mono text-slate-300">.{ext}</td><td className="px-2 py-1 text-slate-500">{v.route}</td></tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </details>

              {error && <div className="rounded-lg border border-rose-500/30 bg-rose-500/10 px-3 py-2 text-xs text-rose-300">{error}</div>}

              <button onClick={runWorkflow} disabled={running} className="w-full rounded-lg bg-cyan-500 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-400 disabled:opacity-50 disabled:cursor-not-allowed">
                {running ? 'Running workflow…' : '▶ Run CAD → SimReady workflow'}
              </button>
            </div>
          </div>

          <SlopeDemo />
        </div>

        {/* RIGHT — pipeline */}
        <div className="space-y-4">
          <div className="solid-card rounded-xl p-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold">Workflow pipeline · 18 stages</h3>
              <span className="rounded-full border border-slate-700 px-2 py-0.5 font-mono text-[11px] text-slate-500">{inputs.propertyAssignmentIntent === 'skip' ? 'conversion-only' : 'end-to-end'}</span>
            </div>
            <div className="mt-3 space-y-1.5">
              {(stages ?? WORKFLOW_STEPS.map((s) => ({ stage: s.id, title: s.label, status: 'pending' as const }))).map((st, idx) => {
                const meta = STATUS_META[st.status]
                const spec = WORKFLOW_STEPS[idx]
                return (
                  <div key={st.stage} className={`flex items-center gap-3 rounded-lg border px-3 py-2 text-xs ${meta.cls}`}>
                    <span className={`h-2 w-2 shrink-0 rounded-full ${meta.dot}`} aria-hidden />
                    <span className="min-w-0 flex-1 truncate font-medium">{spec.label}</span>
                    <span className="hidden font-mono text-[11px] opacity-60 sm:inline">{spec.ref}</span>
                    <span className="shrink-0 rounded bg-slate-900 px-1.5 py-0.5 font-mono text-[10px] leading-none">{meta.label}</span>
                  </div>
                )
              })}
            </div>
            {stages?.some((s) => s.status === 'running') && <div className="mt-3 h-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-1/3 animate-[shimmer_1.2s_ease_infinite] bg-gradient-to-r from-cyan-400 via-violet-400 to-cyan-400" /></div>}
          </div>

          {report && (
            <>
              <div className="solid-card rounded-xl p-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold">Render preview</h3>
                  <span className="text-[11px] text-slate-500">{inputs.simreadyProfile}</span>
                </div>
                <div className="mt-3 overflow-hidden rounded-xl border border-slate-800 bg-[#050508]">
                  {/* Placeholder OVRTX render — black background per spec; swap with real PNG when backend serves it */}
                  <div className="flex aspect-[16/9] items-center justify-center bg-[#050508] p-6">
                    <div className="text-center">
                      <div className="mx-auto grid h-20 w-20 place-items-center rounded-xl border border-cyan-500/20 bg-slate-900 text-2xl">⬢</div>
                      <div className="mt-2 font-mono text-xs text-slate-400">{report.render_preview_path ?? 'no preview (disabled)'}</div>
                      <div className="mt-1 text-[11px] text-slate-600">Terrain USD — Prop-Robotics-Neutral · NER shale hill · 1.8M tris</div>
                    </div>
                  </div>
                </div>
                {report.deliverable_root && (
                  <div className="mt-3 rounded-lg border border-slate-800 bg-slate-900/50 p-3 font-mono text-[11px] leading-relaxed text-slate-400">
                    <div className="font-semibold text-slate-300">Deliverable (two-zone layout)</div>
                    <div>{report.deliverable_root}/</div>
                    <div className="pl-3">simready_usd/sm_{inputs.packageName}_01.usd</div>
                    <div className="pl-3">.thumbs/256x256/thumbnail.png</div>
                    <div className="mt-1 text-slate-500">Pass <code className="font-mono text-[10px]">deliverable/</code> to <code className="font-mono text-[10px]">nv-core-package-sample --root-usd simready_usd/sm_*.usd</code> (never pipeline root).</div>
                  </div>
                )}
              </div>

              <div className="solid-card rounded-xl p-4">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-bold">Validation gates</h3>
                  <span className={`rounded-full border px-2 py-0.5 text-xs font-semibold ${report.passed ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-300' : report.needs_rerun ? 'border-amber-500/30 bg-amber-500/10 text-amber-300' : 'border-rose-500/30 bg-rose-500/10 text-rose-300'}`}>
                    {report.passed ? 'passed' : report.needs_rerun ? 'needs_rerun' : 'blocked'}
                  </span>
                </div>
                <div className="mt-3 overflow-hidden rounded-lg border border-slate-800">
                  <table className="w-full text-left text-xs">
                    <thead><tr className="bg-slate-900 text-slate-400"><th className="px-3 py-2">Gate</th><th className="px-3 py-2">Req</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Findings</th></tr></thead>
                    <tbody>
                      {report.validation_gates.map((g) => (
                        <tr key={g.id} className="odd:bg-slate-900/30"><td className="px-3 py-1.5 font-mono text-slate-200">{g.id}</td><td className="px-3 py-1.5 text-slate-400">{g.requirement}</td><td className="px-3 py-1.5"><span className={`rounded px-1.5 py-0.5 font-mono text-[11px] ${g.status === 'passed' ? 'bg-emerald-500/15 text-emerald-300' : g.status === 'needs_rerun' ? 'bg-amber-500/15 text-amber-300' : 'bg-slate-800 text-slate-400'}`}>{g.status}</span></td><td className="px-3 py-1.5 text-slate-400">{g.findings}</td></tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {report.rerun_reasons.length > 0 && (
                  <div className="mt-3 rounded-lg border border-amber-500/20 bg-amber-500/5 px-3 py-2 text-xs text-amber-200">
                    <div className="font-semibold">Rerun reasons</div>
                    <ul className="mt-1 list-disc pl-5 text-amber-200/80">{report.rerun_reasons.map((r) => <li key={r}>{r} — rerun simready-conform-profile via FET005 with vision-selected grasp points</li>)}</ul>
                  </div>
                )}
                <div className="mt-3 flex gap-2">
                  <button onClick={downloadJson} className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:bg-slate-800">⬇ JSON report</button>
                  <button onClick={downloadMd} className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-1.5 text-xs font-semibold text-slate-200 hover:bg-slate-800">⬇ Markdown report</button>
                </div>
              </div>

              <div className="solid-card rounded-xl p-4">
                <h3 className="text-sm font-bold">Consolidated report (workflow §18)</h3>
                <div className="mt-3"><ReportMarkdown report={report} /></div>
              </div>
            </>
          )}

          {!report && !stages && (
            <div className="solid-card rounded-xl p-8 text-center">
              <div className="mx-auto grid h-14 w-14 place-items-center rounded-xl border border-slate-800 bg-slate-900 text-xl">⬢</div>
              <div className="mt-3 text-sm font-semibold text-slate-200">Select a source asset to begin</div>
              <div className="mx-auto mt-1 max-w-sm text-xs leading-relaxed text-slate-500">
                Drop a terrain DEM or CAD model — it is converted, validated and packaged into a simulation-ready USD automatically.
              </div>
              <div className="mt-4 rounded-lg border border-cyan-500/20 bg-cyan-500/5 p-3 text-left text-xs leading-relaxed text-cyan-100/80">
                <div className="font-semibold text-cyan-200">Tip</div>
                Upload a DEM GeoTIFF plus a design STEP (e.g., retaining wall). The lab converts the terrain to simulation-ready USD with physics colliders — ready for landslide runout simulation on that hillslope.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
